import assaultIcon from '@shared/assets/images/classes/class_assault.svg?component';
import engineerIcon from '@shared/assets/images/classes/class_engineer_long_war.svg?component';
import gunnerIcon from '@shared/assets/images/classes/class_heavy.svg?component';
import infantryIcon from '@shared/assets/images/classes/class_infantry_long_war.svg?component';
import rocketeerIcon from '@shared/assets/images/classes/class_rocketeer_long_war.svg?component';
import scoutIcon from '@shared/assets/images/classes/class_scout_long_war.svg?component';
import sniperIcon from '@shared/assets/images/classes/class_sniper.svg?component';
import medicIcon from '@shared/assets/images/classes/class_support.svg?component';

import type { SoldierClass } from '../../model/types';
import { ABILITY_ID } from './ability-id';
import { SOLDIER_CLASS_ID } from './soldier-class-id';
import { SOLDIER_RANK_ID } from './soldier-rank-id';

export const SOLDIER_CLASSES: SoldierClass[] = [
  {
    id: SOLDIER_CLASS_ID.SNIPER,
    name: 'Sniper',
    icon: sniperIcon,
    abilities: {
      [SOLDIER_RANK_ID.SPECIALIST]: [ABILITY_ID.SQUADSIGHT],
      [SOLDIER_RANK_ID.LANCE_CORPORAL]: [ABILITY_ID.MAGNUM, ABILITY_ID.ON_THE_READY, ABILITY_ID.IN_THE_ZONE],
      [SOLDIER_RANK_ID.CORPORAL]: [ABILITY_ID.SHARPSHOOTER, ABILITY_ID.OPPORTUNIST, ABILITY_ID.DISABLING_SHOT],
      [SOLDIER_RANK_ID.SERGEANT]: [ABILITY_ID.RANGER, ABILITY_ID.SHADOWSTEP, ABILITY_ID.EXECUTIONER],
      [SOLDIER_RANK_ID.TECH_SERGEANT]: [ABILITY_ID.PRECISION_SHOT],
      [SOLDIER_RANK_ID.GUNNERY_SERGEANT]: [ABILITY_ID.IMPACT, ABILITY_ID.VITAL_POINT_TARGETING, ABILITY_ID.BRING_EM_ON],
      [SOLDIER_RANK_ID.MASTER_SERGEANT]: [ABILITY_ID.EXTRA_CONDITIONING, ABILITY_ID.LONE_WOLF],
    },
  },
  {
    id: SOLDIER_CLASS_ID.SCOUT,
    name: 'Scout',
    icon: scoutIcon,
    abilities: {
      [SOLDIER_RANK_ID.SPECIALIST]: [ABILITY_ID.RECONNAISSANCE],
      [SOLDIER_RANK_ID.LANCE_CORPORAL]: [ABILITY_ID.BULLSEYE, ABILITY_ID.HIT_AND_RUN, ABILITY_ID.SMOKE_AND_MIRRORS],
      [SOLDIER_RANK_ID.CORPORAL]: [ABILITY_ID.SNAPSHOT, ABILITY_ID.RANGER, ABILITY_ID.DISABLING_SHOT],
      [SOLDIER_RANK_ID.SERGEANT]: [ABILITY_ID.IMPACT, ABILITY_ID.VITAL_POINT_TARGETING, ABILITY_ID.TINKER],
      [SOLDIER_RANK_ID.TECH_SERGEANT]: [ABILITY_ID.PATHFINDER],
      [SOLDIER_RANK_ID.GUNNERY_SERGEANT]: [ABILITY_ID.PRECISION_SHOT, ABILITY_ID.SHADOWSTEP, ABILITY_ID.KITTED],
      [SOLDIER_RANK_ID.MASTER_SERGEANT]: [ABILITY_ID.AGGRESSION, ABILITY_ID.EXTRA_CONDITIONING],
    },
  },
  {
    id: SOLDIER_CLASS_ID.INFANTRY,
    name: 'Infantry',
    icon: infantryIcon,
    abilities: {
      [SOLDIER_RANK_ID.SPECIALIST]: [ABILITY_ID.LIGHT_EM_UP],
      [SOLDIER_RANK_ID.LANCE_CORPORAL]: [ABILITY_ID.WILL_TO_SURVIVE, ABILITY_ID.SENTINEL, ABILITY_ID.GRENADIER],
      [SOLDIER_RANK_ID.CORPORAL]: [ABILITY_ID.TENACIOUS_DEFENSE, ABILITY_ID.LOCK_N_LOAD, ABILITY_ID.PAYLOAD],
      [SOLDIER_RANK_ID.SERGEANT]: [ABILITY_ID.EXTRA_CONDITIONING, ABILITY_ID.IMPACT, ABILITY_ID.KITTED],
      [SOLDIER_RANK_ID.TECH_SERGEANT]: [ABILITY_ID.ACE],
      [SOLDIER_RANK_ID.GUNNERY_SERGEANT]: [ABILITY_ID.BRING_EM_ON, ABILITY_ID.RANGER, ABILITY_ID.TANDEM_WARHEADS],
      [SOLDIER_RANK_ID.MASTER_SERGEANT]: [ABILITY_ID.EXECUTIONER, ABILITY_ID.AGGRESSION],
    },
  },
  {
    id: SOLDIER_CLASS_ID.ASSAULT,
    name: 'Assault',
    icon: assaultIcon,
    abilities: {
      [SOLDIER_RANK_ID.SPECIALIST]: [ABILITY_ID.CLOSE_ENCOUNTERS],
      [SOLDIER_RANK_ID.LANCE_CORPORAL]: [ABILITY_ID.WILL_TO_SURVIVE, ABILITY_ID.RUN_AND_GUN, ABILITY_ID.BREACHER],
      [SOLDIER_RANK_ID.CORPORAL]: [ABILITY_ID.EXTRA_CONDITIONING, ABILITY_ID.BRAWLER, ABILITY_ID.FRAGMENTATION],
      [SOLDIER_RANK_ID.SERGEANT]: [ABILITY_ID.PISTOLERO, ABILITY_ID.RANGER, ABILITY_ID.KILLER_INSTINCT],
      [SOLDIER_RANK_ID.TECH_SERGEANT]: [ABILITY_ID.RAPID_FIRE],
      [SOLDIER_RANK_ID.GUNNERY_SERGEANT]: [ABILITY_ID.TENACIOUS_DEFENSE, ABILITY_ID.AGGRESSION, ABILITY_ID.HEAT_WARHEADS],
      [SOLDIER_RANK_ID.MASTER_SERGEANT]: [ABILITY_ID.SPRINTER, ABILITY_ID.LOCK_N_LOAD],
    },
  },
  {
    id: SOLDIER_CLASS_ID.GUNNER,
    name: 'Gunner',
    icon: gunnerIcon,
    abilities: {
      [SOLDIER_RANK_ID.SPECIALIST]: [ABILITY_ID.SUPPRESSION],
      [SOLDIER_RANK_ID.LANCE_CORPORAL]: [ABILITY_ID.WILL_TO_SURVIVE, ABILITY_ID.RAKING_FIRE, ABILITY_ID.MAYHEM],
      [SOLDIER_RANK_ID.CORPORAL]: [ABILITY_ID.DOUBLE_TAP, ABILITY_ID.READY_FOR_ANYTHING, ABILITY_ID.HOLO_ROUNDS],
      [SOLDIER_RANK_ID.SERGEANT]: [ABILITY_ID.GRIT, ABILITY_ID.CRITICAL_SYSTEM_TARGETING, ABILITY_ID.PENETRATOR],
      [SOLDIER_RANK_ID.TECH_SERGEANT]: [ABILITY_ID.EXTRA_CONDITIONING],
      [SOLDIER_RANK_ID.GUNNERY_SERGEANT]: [ABILITY_ID.TENACIOUS_DEFENSE, ABILITY_ID.BRING_EM_ON, ABILITY_ID.LOCK_N_LOAD],
      [SOLDIER_RANK_ID.MASTER_SERGEANT]: [ABILITY_ID.KITTED, ABILITY_ID.IMPACT],
    },
  },
  {
    id: SOLDIER_CLASS_ID.ROCKETEER,
    name: 'Rocketeer',
    icon: rocketeerIcon,
    abilities: {
      [SOLDIER_RANK_ID.SPECIALIST]: [ABILITY_ID.FIRE_ROCKET],
      [SOLDIER_RANK_ID.LANCE_CORPORAL]: [ABILITY_ID.LIGHT_EM_UP, ABILITY_ID.GRENADIER, ABILITY_ID.SMOKE_AND_MIRRORS],
      [SOLDIER_RANK_ID.CORPORAL]: [ABILITY_ID.HOLO_ROUNDS, ABILITY_ID.BLAST, ABILITY_ID.KITTED],
      [SOLDIER_RANK_ID.SERGEANT]: [ABILITY_ID.RANGER, ABILITY_ID.SAPPER, ABILITY_ID.ACID_TECH],
      [SOLDIER_RANK_ID.TECH_SERGEANT]: [ABILITY_ID.SHOCK_AND_AWE],
      [SOLDIER_RANK_ID.GUNNERY_SERGEANT]: [ABILITY_ID.HEAT_WARHEADS, ABILITY_ID.FRAGMENTATION, ABILITY_ID.TANDEM_WARHEADS],
      [SOLDIER_RANK_ID.MASTER_SERGEANT]: [ABILITY_ID.BRING_EM_ON, ABILITY_ID.EXTRA_CONDITIONING],
    },
  },
  {
    id: SOLDIER_CLASS_ID.MEDIC,
    name: 'Medic',
    icon: medicIcon,
    abilities: {
      [SOLDIER_RANK_ID.SPECIALIST]: [ABILITY_ID.FIELD_MEDIC],
      [SOLDIER_RANK_ID.LANCE_CORPORAL]: [ABILITY_ID.WILL_TO_SURVIVE, ABILITY_ID.SENTINEL, ABILITY_ID.SMOKE_AND_MIRRORS],
      [SOLDIER_RANK_ID.CORPORAL]: [ABILITY_ID.RAPID_PINCERS, ABILITY_ID.GUARDIAN, ABILITY_ID.COMBAT_DRUGS],
      [SOLDIER_RANK_ID.SERGEANT]: [ABILITY_ID.SUSTAIN, ABILITY_ID.SURGICAL_TARGETING, ABILITY_ID.RANGER],
      [SOLDIER_RANK_ID.TECH_SERGEANT]: [ABILITY_ID.SAVIOR],
      [SOLDIER_RANK_ID.GUNNERY_SERGEANT]: [ABILITY_ID.PISTOLERO, ABILITY_ID.BRING_EM_ON, ABILITY_ID.HOLO_ROUNDS],
      [SOLDIER_RANK_ID.MASTER_SERGEANT]: [ABILITY_ID.EXTRA_CONDITIONING, ABILITY_ID.SHARPSHOOTER],
    },
  },
  {
    id: SOLDIER_CLASS_ID.ENGINEER,
    name: 'Engineer',
    icon: engineerIcon,
    abilities: {
      [SOLDIER_RANK_ID.SPECIALIST]: [ABILITY_ID.MECHANIC],
      [SOLDIER_RANK_ID.LANCE_CORPORAL]: [ABILITY_ID.DOUBLE_TAP, ABILITY_ID.GRENADIER, ABILITY_ID.SMOKE_AND_MIRRORS],
      [SOLDIER_RANK_ID.CORPORAL]: [ABILITY_ID.HOLO_ROUNDS, ABILITY_ID.SAPPER, ABILITY_ID.FIREBASE],
      [SOLDIER_RANK_ID.SERGEANT]: [ABILITY_ID.CRITICAL_SYSTEM_TARGETING, ABILITY_ID.TANDEM_WARHEADS, ABILITY_ID.DENSE_SMOKE],
      [SOLDIER_RANK_ID.TECH_SERGEANT]: [ABILITY_ID.MASTER_MECHANIC],
      [SOLDIER_RANK_ID.GUNNERY_SERGEANT]: [ABILITY_ID.BRING_EM_ON, ABILITY_ID.HEAT_WARHEADS, ABILITY_ID.ACID_TECH],
      [SOLDIER_RANK_ID.MASTER_SERGEANT]: [ABILITY_ID.LOCK_N_LOAD, ABILITY_ID.EXTRA_CONDITIONING],
    },
  },
];
